version: '3'
services:
  postgres:
    container_name: db
    build:
      dockerfile: ./db/Dockerfile
    environment:
      - POSTGRES_PASSWORD=root1234
      - POSTGRES_USER=postgres
    networks:
      - app_network
    restart: always

  app:
    container_name: app
    build:
      dockerfile: ./cmd/app/Dockerfile
    ports:
      - 80:80
    depends_on:
      - postgres
    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge
