version: '3'
services:
  tarantool:
    container_name: db
    image: tarantool/tarantool
    command: tarantool /usr/local/share/tarantool/init.lua
    volumes:
      - ./db:/usr/local/share/tarantool
    networks:
      - app_network
    restart: always

  app:
    container_name: app
    build:
      dockerfile: ./cmd/app/Dockerfile
    ports:
      - 80:80
    depends_on:
      - tarantool
    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge
