version: '3'

tasks:
  run:
    cmds:
      - go run cmd/app/main.go
    
  test:
    cmds:
      - go test -v ./...

  lint:
    cmds:
      - golangci-lint run

  docker-build:
    cmds:
      - docker build -t vk-db -f db/Dockerfile .
      - docker build -t vk-app -f cmd/app/Dockerfile .
